CREATE TABLE TASK(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATE_CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    USER_STORY_ID BIGINT NOT NULL
);

CREATE TABLE TASK_USER(
    TASK_PARTICIPANTS_ID BIGINT,
    USER_ID BIGINT
);   